import { ChangeDetectionStrategy, Component } from '@angular/core';
import {
  Brain,
  Briefcase,
  Calendar,
  Camera,
  ChartGantt,
  ClipboardList,
  Clock,
  Coins,
  Cpu,
  Crown,
  Handshake,
  Heart,
  HeartPulse,
  LucideAngularModule,
  Megaphone,
  Mic,
  MicVocal,
  Network,
  Palette,
  Rocket,
  Shield,
  Sparkles,
  Star,
  TrendingUp,
  UserCircle,
  Users,
  Video,
} from 'lucide-angular';

@Component({
  selector: 'app-landing-services',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [LucideAngularModule],
  templateUrl: './services.html',
})
export class LandingServices {
  readonly icons = {
    Brain,
    Briefcase,
    Calendar,
    Camera,
    ChartGantt,
    ClipboardList,
    Clock,
    Coins,
    Cpu,
    Crown,
    Handshake,
    Heart,
    HeartPulse,
    Megaphone,
    Mic,
    MicVocal,
    Network,
    Palette,
    Rocket,
    Shield,
    Sparkles,
    Star,
    TrendingUp,
    UserCircle,
    Users,
    Video,
  } as const;
}
